routes/web.php
<?php

Route::get('/', function () {
    return redirect()->route('login');
});

Route::get('/home', function(){
  return redirect()->route('dashboard.home.index');
});

Route::middleware('auth')->group(function() {
	Route::name('dashboard.')->prefix('dashboard')->namespace('Dashboard')->group( function() {
		Route::get('/', function(){
			return redirect()->route('dashboard.home.index');
		});
		Route::resource('home', 'HomeController');
	});
	Route::name('setting.')->prefix('setting')->namespace('Setting')->group( function() {
		Route::get('/', function(){
			return redirect()->route('setting.users.index');
		});

		Route::post('users/grid', 'UserController@grid')->name('users.grid');
		Route::resource('users', 'UserController');

		Route::post('log/grid', 'LogController@grid')->name('log.grid');
		Route::resource('log', 'LogController');

		Route::post('roles/grid', 'RoleController@grid')->name('roles.grid');
		Route::patch('roles/saveData/{id}','RoleController@saveData')->name('roles.saveData');
		Route::resource('roles', 'RoleController');
	});
	Route::name('kmeans.')->prefix('kmeans')->namespace('Kmeans')->group( function() {
        Route::post('nilai/grid', 'NilaiAlternatifController@grid')->name('nilai.grid');
        Route::get('nilai/{id}/detail','NilaiAlternatifController@detail')->name('nilai.detail');
		Route::resource('nilai', 'NilaiAlternatifController');

		Route::post('hasil/index', 'HasilKmeansController@index')->name('hasil.index');
		Route::resource('hasil', 'HasilKmeansController');
	});

	Route::name('ahp.')->prefix('ahp')->namespace('Ahp')->group( function() {
		Route::post('kriteria/index', 'AHPKriteriaController@index')->name('kriteria.index');
		Route::patch('kriteria/{id}/simpan','AHPKriteriaController@simpan')->name('kriteria.simpan');
		Route::resource('kriteria', 'AHPKriteriaController');

		Route::post('alternatif/index', 'AHPAlternatifController@index')->name('alternatif.index');
		Route::patch('alternatif/{id}/simpan','AHPAlternatifController@simpan')->name('alternatif.simpan');
		Route::resource('alternatif', 'AHPAlternatifController');
	});

	Route::name('master.')->prefix('master')->namespace('Master')->group( function() {
        Route::post('kriteria/grid', 'KriteriaController@grid')->name('kriteria.grid');
		Route::resource('kriteria', 'KriteriaController');

		Route::post('bantuan/grid', 'BantuanController@grid')->name('bantuan.grid');
		Route::resource('bantuan', 'BantuanController');

		Route::post('cluster/grid', 'ClusterController@grid')->name('cluster.grid');
		Route::get('cluster/detil/{id}','ClusterController@detail')->name('cluster.detail');
		Route::patch('cluster/{id}/simpan','ClusterController@simpan')->name('cluster.simpan');
		Route::resource('cluster', 'ClusterController');

		Route::post('alternatif/grid', 'AlternatifController@grid')->name('alternatif.grid');
		Route::resource('alternatif', 'AlternatifController');
	});
});

Auth::routes();

app/Models/Auths/Role.php
<?php 
namespace App\Models\Auths;

use Illuminate\Database\Eloquent\Model;
use App\Models\Traits\Utilities;


class Role extends Model
{
    use Utilities;

    public $table = 'sys_roles';

    protected $fillable = ['name',];
	
}

app/Http/Controllers/Setting/LogController.php
<?php

namespace App\Http\Controllers\Setting;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use Yajra\DataTables\Facades\DataTables;

use App\Http\Requests\Setting\UserRequest;
use App\Models\SessionLog;

class LogController extends Controller
{
    protected $routes = 'setting.log';

    public function __construct()
    {
        $this->setRoutes($this->routes);
        // Header Grid Datatable
        $this->setTableStruct([
            [
                'data' => 'num',
                'name' => 'num',
                'label' => '#',
                'orderable' => false,
                'searchable' => false,
                'className' => 'text-center',
                'width' => '20px',
            ],
            [
                'data' => 'modul',
                'name' => 'modul',
                'label' => 'Modul',
                'sortable' => true,
                'width' => '150px',
            ],
            [
                'data' => 'sub',
                'name' => 'sub',
                'label' => 'Sub Modul',
                'sortable' => true,
                'width' => '150px',
            ],
            [
                'data' => 'aktivitas',
                'name' => 'aktivitas',
                'label' => 'Aktivitas',
                'sortable' => true,
                'width' => '400px',
            ],
            [
                'data' => 'user',
                'name' => 'user',
                'label' => 'User',
                'className' => 'text-center',
                'sortable' => true,
                'width' => '150px',
            ],
            [
                'data' => 'created_at',
                'name' => 'created_at',
                'label' => 'Dibuat Pada',
                'className' => 'text-center',
                'sortable' => true,
                'width' => '150px',
            ],
        ]);
    }

    public function grid()
    {
        $records = SessionLog::select('*');
        if(!isset(request()->order[0]['column'])) {
              $records->orderBy('created_at','desc');
        }
        if ($modul = request()->modul) {
            $records->where('modul', 'like', '%' . $modul . '%');
        }
        if($sub = request()->sub) {
            $records->where('sub', 'like', '%' . $sub . '%');
        }
        if($user = request()->user) {
        	$records->whereHas('user', function($u) use ($user){
	            $u->where('name', 'like', '%' . $user . '%');
        	});
        }
        return DataTables::of($records->get())
           ->addColumn('num', function ($record) {
               return request()->start;
           })
           ->editColumn('created_at', function ($record) {
               return $record->created_at->diffForHumans();
           })
           ->addColumn('aktivitas', function ($record) {
               return $record->readMoreText('aktivitas', 200);
           })
           ->addColumn('user', function ($record) {
        		return $record->creatorName();
           })
           ->rawColumns(['fungsi', 'action','aktivitas'])
           ->make(true);
    }

    public function index()
    {
        return $this->render('settings.log.index');
    }
}

app/Http/Controllers/Setting/RoleController.php
<?php

namespace App\Http\Controllers\Setting;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Yajra\DataTables\Facades\DataTables;
use App\Http\Requests\Setting\RoleRequest;

use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use App\Models\SessionLog;

class RoleController extends Controller
{
    protected $routes = 'setting.roles';
    protected $perms = 'accident-report';


    public function __construct()
    {
        $this->setRoutes($this->routes);
        // Header Grid Datatable
        $this->setTableStruct([
            [
                'data' => 'num',
                'name' => 'num',
                'label' => '#',
                'orderable' => false,
                'searchable' => false,
                'className' => 'text-center',
                'width' => '20px',
            ],
            /* --------------------------- */
            [
                'data' => 'name',
                'name' => 'name',
                'label' => 'Role',
                'sortable' => true,
            ],
            [
                'data' => 'users',
                'name' => 'users',
                'label' => 'Jumlah User',
                'className' => 'text-center',
                'sortable' => true,
            ],
            [
                'data' => 'perms',
                'name' => 'perms',
                'label' => 'Permissions',
                'className' => 'text-center',
                'sortable' => true,
            ],
            [
                'data' => 'created_at',
                'name' => 'created_at',
                'label' => 'Dibuat Pada',
                'className' => 'text-center',
                'sortable' => true,
            ],
            [
                'data' => 'updated_at',
                'name' => 'updated_at',
                'label' => 'Diperbarui Pada',
                'className' => 'text-center',
                'sortable' => true,
            ],
            [
                'data' => 'action',
                'name' => 'action',
                'label' => 'Aksi',
                'searchable' => false,
                'sortable' => false,
                'width' => '90px',
                'className' => 'text-center'
            ]
        ]);
    }

    public function grid()
    {
        $records = Role::with('users', 'permissions')->when($name = request()->name, function ($q) use ($name) {
            $q->where('name', 'like', '%'.$name.'%');
        })
                        ->select('*');
        $routes = $this->routes;

        return DataTables::of($records->get())
               ->addColumn('num', function ($record) {
                   return request()->start;
               })
               ->addColumn('perms', function ($record) {
                   return $record->permissions->count().' Permissions';
               })
               ->addColumn('users', function ($record) {
                   return $record->users->count().' Users';
               })
               ->editColumn('created_at', function ($record) {
                   return $record->created_at->diffForHumans();
               })
               ->editColumn('updated_at', function ($record) {
                   return $record->updated_at->diffForHumans();
               })
               ->addColumn('action', function ($record) use ($routes) {
                   $buttons = '';

                   $buttons .= $this->makeButton([
                        'type'    => 'url',
                        'class'   => auth()->user()->can($this->perms.'-edit') ? '' : 'm-r',
                        'label'   => '<i class="fa fa-check-square text-success"></i>',
                        'tooltip' => 'Assign Permissions',
                        'url'  => route($routes.'.show', $record->id),
                    ]);
				   if($record->users()->count() <= 0){
	                   if (!auth()->user()->can($this->perms.'-edit')) {
		                    $buttons .= $this->makeButton([
	                            'type' => 'edit',
	                            'id'   => $record->id,
	                        ]);
	                        $buttons .= $this->makeButton([
	                            'type' => 'delete',
	                            'id'   => $record->id,
	                        ]);
	                   }
	                }else{
	                	if (!auth()->user()->can($this->perms.'-edit')) {
	                        $buttons .= $this->makeButton([
	                            'type' => 'delete',
	                            'id'   => $record->id,
	                        ]);
	                   }
	                }

                   return $buttons;
               })
               ->make(true);
    }

    public function index()
    {
        return $this->render('settings.role.index');
    }

    public function create()
    {
        return $this->render('settings.role.create');
    }

    public function store(RoleRequest $request)
    {	
    	$user = auth()->user();
    	$log = new SessionLog;
	    $log->modul = 'Manajemen Pengguna';
	    $log->sub = 'Role';
	    $log->aktivitas = 'Membuat Role baru dengan nama '.request('name');
	    $log->user_id = $user->id;
	    $log->save();
        return Role::create(request(['name']));
    }

    public function show(Role $role)
    {
        return $this->render('settings.role.detail', ['record' => $role]);
    }

    public function edit(Role $role)
    {
        return $this->render('settings.role.edit', ['record' => $role]);
    }

    public function update(Role $role)
    {
        foreach (request()->check as $key => $value) {
            $temp = [
                'name' => $value,
            ];
            if(Permission::where('name', $value)->count() == 0){
                Permission::create($temp);
            }
        }
        $permsi = Permission::whereIn('name', request()->check)->get()->pluck('id');
        $record = Role::findById(request()->id);
        $record->permissions()->sync($permsi);
        app()->make(\Spatie\Permission\PermissionRegistrar::class)->forgetCachedPermissions();
        
        return response([
            'status' => true
        ]);
    }

    public function saveData(RoleRequest $request)
    {
    	$record = Role::find($request->id);
    	$name = $record->name;
        $record->name = $request->name;
        $record->save();

    	$user = auth()->user();
    	$log = new SessionLog;
	    $log->modul = 'Manajemen Pengguna';
	    $log->sub = 'Role';
	    $log->aktivitas = 'Mengubah '.$name.' menjadi '.$request->name;
	    $log->user_id = $user->id;
	    $log->save();
        return response([
            'status' => true
        ]);
    }

    public function destroy(Role $role)
    {
    	if($role->users()->count() > 0){
    		return response([
                'status' => 500,
            ],500);
    	}else{
    		$user = auth()->user();
	    	$log = new SessionLog;
		    $log->modul = 'Manajemen Pengguna';
		    $log->sub = 'Role';
		    $log->aktivitas = 'Menghapus Role '.$role->name;
		    $log->user_id = $user->id;
		    $log->save();

	        $role->delete();
	        return response()->json([
	            'success' => true
	        ]);
    	}

    }
}

resources/views/settings/role/create.blade.php
<form action="{{ route($routes.'.store') }}" method="POST" id="formData">
    @csrf

    <div class="modal-header">
        <h5 class="modal-title" style="font-weight: bold;">Tambah Data Role</h5>
    </div>
    <div class="modal-body">
        {{-- <p class="text-muted">Please fill the information to continue</p> --}}
        <div class="form-group">
            <label class="control-label">Role</label>
            <input type="text" name="name" class="form-control" placeholder="Role" required="">
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-cancel" data-dismiss="modal">Kembali</button>
        <button type="button" class="btn btn-simpan save button">Simpan</button>
    </div>

    <div class="loading dimmer padder-v">
        <div class="loader"></div>
    </div>
</form>

resources/views/settings/role/detail.blade.php
@extends('layouts.base')

@include('libs.actions')

@section('title', 'Manajemen Pengguna')

@section('side-header')
    <div class="btn-group" style="left: -15px;">
        <a href="{{ route('setting.users.index') }}" type="button" class="btn btn-default" style="border-radius: 20px;">User</a>
        <a href="{{ route('setting.roles.index') }}" type="button" class="btn btn-violet" style="border-radius: 20px;">Role</a>
    </div>
@endsection

@section('body')
	<form id="formData" action="{{ route($routes.'.update', $record->id) }}" method="POST">
		@method('PATCH')
		@csrf
		
		<input type="hidden" name="name" value="{{ $record->name }}">
		<input type="hidden" name="id" value="{{ $record->id }}">
		<div class="panel panel-default" style="font-size: 12px;">
			<div class="panel-heading" style="background-color: #0f2233;">
				<h4 class="font-thin h4">
					<span style="color: white;font-size: 16px;font-weight: bold;">Role : {{ $record->name }}</span>
					<span class="pull-right" style="color: white;font-size: 16px;font-weight: bold;">{{ $record->users->count() }} Users</span>
				</h4>
			</div>
			<table class="table table-striped b-t b-light">
				<thead>
					<tr>
						<th><i class="fa fa-dedent fa-fw text"></i>&nbsp;&nbsp;&nbsp;Menu</th>
						<th class="text-center">View</th>
						<th class="text-center">Create</th>
						<th class="text-center">Update</th>
						<th class="text-center">Delete</th>
						<th class="text-center"></th>
					</tr>
				</thead>
				@foreach($sideMenu->roots() as $item)
				@php
					if(is_array($item->perms))
					{
						$perms = \App\Models\Auths\Permission::where(function($query) use ($item) {
								for($i = 0; $i < count($item->perms); $i++)
								{
										$query->orWhere('name', 'like', $item->perms[$i].'%');
								}
						})->get();
					}else{
						$perms = \App\Models\Auths\Permission::where('name', 'like', $item->perms.'%')->get();
					}
				@endphp
					<thead>
						<tr style="background-color: #f0f0f0;">
							<th><i class="{{ $item->data['icon'] }} icon"></i>&nbsp;&nbsp;&nbsp;{{ $item->title}}</th>
							<th class="text-center">
								@if($item->hasChildren())
									<button type="button" class="btn btn-xs btn-default vertical all" style="border-radius: 20px;" data-action="view">&nbsp;&nbsp;<i class="fa fa-check"></i>&nbsp;&nbsp; View All&nbsp;&nbsp;&nbsp;</button>
								@else
									@if($p = $perms->where('name', $item->perms.'-view')->first())
										<input type="checkbox" class="view check" name="check[]" value="{{ $p->name }}" @if($record->hasPermissionTo($item->perms.'-view')) checked @endif data-toggle="toggle" data-size="mini" data-on="Ya" data-off="Tidak" data-style="ios">
									@else
										<input type="checkbox" class="view check" name="check[]" value="{{ $item->perms.'-view' }}" data-toggle="toggle" data-size="mini" data-on="Ya" data-off="Tidak" data-style="ios">
									@endif
								@endif
							</th>
							<th class="text-center">
								@if($item->hasChildren())
									<button type="button" class="btn btn-xs btn-default vertical all" style="border-radius: 20px;" data-action="create">&nbsp;&nbsp;<i class="fa fa-check"></i>&nbsp;&nbsp; Create All&nbsp;&nbsp;&nbsp;</button>
								@else
									@if($p = $perms->where('name', $item->perms.'-add')->first())
										<input type="checkbox" class="create check" name="check[]" value="{{ $p->name }}" @if($record->hasPermissionTo($item->perms.'-add')) checked @endif data-toggle="toggle" data-size="mini" data-on="Ya" data-off="Tidak" data-style="ios">
									@else
										<input type="checkbox" class="create check" name="check[]" value="{{ $item->perms.'-add' }}" data-toggle="toggle" data-size="mini" data-on="Ya" data-off="Tidak" data-style="ios">
									@endif
								@endif
							</th>
							<th class="text-center">
								@if($item->hasChildren())
									<button type="button" class="btn btn-xs btn-default vertical all" style="border-radius: 20px;" data-action="update">&nbsp;&nbsp;<i class="fa fa-check"></i>&nbsp;&nbsp; Update All&nbsp;&nbsp;&nbsp;</button>
								@else
									@if($p = $perms->where('name', $item->perms.'-edit')->first())
										<input type="checkbox" class="update check" name="check[]" value="{{ $p->name }}" @if($record->hasPermissionTo($item->perms.'-edit')) checked @endif data-toggle="toggle" data-size="mini" data-on="Ya" data-off="Tidak" data-style="ios">
									@else
										<input type="checkbox" class="update check" name="check[]" value="{{ $item->perms.'-edit' }}" data-toggle="toggle" data-size="mini" data-on="Ya" data-off="Tidak" data-style="ios">
									@endif
								@endif
							</th>
							<th class="text-center">
								@if($item->hasChildren())
									<button type="button" class="btn btn-xs btn-default vertical all" style="border-radius: 20px;" data-action="delete">&nbsp;&nbsp;<i class="fa fa-check"></i>&nbsp;&nbsp; Delete All&nbsp;&nbsp;&nbsp;</button>
								@else
									@if($p = $perms->where('name', $item->perms.'-delete')->first())
										<input type="checkbox" class="delete check" name="check[]" value="{{ $p->name }}" @if($record->hasPermissionTo($item->perms.'-delete')) checked @endif data-toggle="toggle" data-size="mini" data-on="Ya" data-off="Tidak" data-style="ios">
									@else
										<input type="checkbox" class="delete check" name="check[]" value="{{ $item->perms.'-delete' }}" data-toggle="toggle" data-size="mini" data-on="Ya" data-off="Tidak" data-style="ios">
									@endif
								@endif
							</th>
							<th class="text-center">
								@if($item->hasChildren())
								@else
									<button type="button" class="btn btn-xs btn-default horizontal all" style="border-radius: 20px;">&nbsp;&nbsp;<i class="fa fa-check"></i>&nbsp;&nbsp; Check All&nbsp;&nbsp;&nbsp;</button>
								@endif
							</th>
						</tr>
					</thead>
					@if($item->hasChildren())
					<tbody>
						@foreach($item->children() as $child)
							@php
								$perms = \App\Models\Auths\Permission::where('name', 'like', $child->perms.'%')->get();
							@endphp
							<tr>
								<td style="padding-left: 33px;">{{ $child->title}}</td>
								<td class="text-center">
									@if($p = $perms->where('name', $child->perms.'-view')->first())
										<input type="checkbox" class="view check" name="check[]" value="{{ $p->name }}" @if($record->hasPermissionTo($child->perms.'-view')) checked @endif data-toggle="toggle" data-size="mini" data-on="Ya" data-off="Tidak" data-style="ios">
									@else
										<input type="checkbox" class="view check" name="check[]" value="{{ $child->perms.'-view' }}" data-toggle="toggle" data-size="mini" data-on="Ya" data-off="Tidak" data-style="ios">
									@endif
								</td>
								<td class="text-center">
									@if($p = $perms->where('name', $child->perms.'-add')->first())
										<input type="checkbox" class="create check" name="check[]" value="{{ $p->name }}" @if($record->hasPermissionTo($child->perms.'-add')) checked @endif data-toggle="toggle" data-size="mini" data-on="Ya" data-off="Tidak" data-style="ios">
									@else
										<input type="checkbox" class="create check" name="check[]" value="{{ $child->perms.'-add' }}" data-toggle="toggle" data-size="mini" data-on="Ya" data-off="Tidak" data-style="ios">
									@endif
								</td>
								<td class="text-center">
									@if($p = $perms->where('name', $child->perms.'-edit')->first())
										<input type="checkbox" class="update check" name="check[]" value="{{ $p->name }}" @if($record->hasPermissionTo($child->perms.'-edit')) checked @endif data-toggle="toggle" data-size="mini" data-on="Ya" data-off="Tidak" data-style="ios">
									@else
										<input type="checkbox" class="update check" name="check[]" value="{{ $child->perms.'-edit' }}" data-toggle="toggle" data-size="mini" data-on="Ya" data-off="Tidak" data-style="ios">
									@endif
								</td>
								<td class="text-center">
									@if($p = $perms->where('name', $child->perms.'-delete')->first())
										<input type="checkbox" class="delete check" name="check[]" value="{{ $p->name }}" @if($record->hasPermissionTo($child->perms.'-delete')) checked @endif data-toggle="toggle" data-size="mini" data-on="Ya" data-off="Tidak" data-style="ios">
									@else
										<input type="checkbox" class="delete check" name="check[]" value="{{ $child->perms.'-delete' }}" data-toggle="toggle" data-size="mini" data-on="Ya" data-off="Tidak" data-style="ios">
									@endif
								</td>
								<td class="text-center">
									<button type="button" class="btn btn-xs btn-default horizontal all" style="border-radius: 20px;">&nbsp;&nbsp;<i class="fa fa-check"></i>&nbsp;&nbsp; Check All&nbsp;&nbsp;&nbsp;</button>
								</td>
							</tr>
						@endforeach
					</tbody>
					@endif
				@endforeach
			</table>
			<div class="panel-footer">
				<a href="{{ url()->previous() }}" class="btn btn-sm btn-default" style="border-radius: 20px;">
					<i class="fa fa-angle-left"></i>&nbsp;&nbsp; Kembali
				</a>
				<button type="button" class="btn btn-sm btn btn-simpan pull-right save button">
					<i class="fa fa-save"></i>&nbsp;&nbsp; Simpan
				</button>
			</div>
		</div>
	    <div class="loading dimmer padder-v" style="display: none">
	        <div class="loader"></div>
	    </div>
	</form>
@endsection

@push('scripts')
<script>
	$(document).on('click', '.vertical.all', function(e){
		e.preventDefault();
		var container 	= $(this).closest('thead');
		var action 		= $(this).data('action');
		var selector	= $('.'+action+'.check');
		var checked		= true;
		container.next('tbody').find(selector).each(function(e){
			checked = this.checked = !this.checked;
			// $(this).prop('checked', !$(this).prop('checked'));
		});
		container.next('tbody').find(selector).trigger('click');
	});

	$(document).on('click', '.horizontal.all', function(e){
		e.preventDefault();
		var container 	= $(this).closest('tr');
		var selector	= $('.check');
		var checked		= true;
		container.find(selector).each(function(e){
			checked = this.checked = !this.checked;
			// $(this).prop('checked', !$(this).prop('checked'));
		});

		container.find(selector).trigger('click');
	});

    $(document).on('click', '.save.button', function(e){
        saveData('formData', function(resp){
            location.href = "{{ route($routes.'.index') }}";
        });
    });
</script>
@endpush

resources/views/settings/role/edit.blade.php
<form action="{{ route($routes.'.saveData', $record->id) }}" method="POST" id="formData">
    @method('PATCH')
    @csrf
    <input type="hidden" name="id" value="{{ $record->id }}">

    <div class="modal-header">
        <h5 class="modal-title" style="font-weight: bold;">Ubah Data Role</h5>
    </div>
    <div class="modal-body">
        {{-- <p class="text-muted">Please fill the information to continue</p> --}}
        <div class="form-group">
            <label class="control-label">Role</label>
            <input type="text" name="name" class="form-control" placeholder="Role" value="{{ $record->name }}" required>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-cancel" data-dismiss="modal">Kembali</button>
        <button type="button" class="btn btn-simpan save button">Simpan</button>
    </div>

    <div class="loading dimmer padder-v">
        <div class="loader"></div>
    </div>
</form>

resources/views/settings/role/index.blade.php
@extends('layouts.list')

@section('title', 'Manajemen Pengguna')

@section('side-header')
    <div class="btn-group" style="left: -15px;">
        <a href="{{ route('setting.users.index') }}" type="button" class="btn btn-grey ada" style="border-radius: 20px;">User</a>
        <a href="{{ route('setting.roles.index') }}" type="button" class="btn btn-grey ada active" style="border-radius: 20px;">Role</a>
        <a href="{{ route('setting.log.index') }}" type="button" class="btn btn-grey hilang" style="border-radius: 20px;">Log</a>
    </div>
@endsection

@section('filters')
    <div class="form-group">
        <label class="control-label m-r-sm" for="filters"><i class="fa fa-filter"></i> &nbsp; Filter</label>
        <label class="control-label sr-only" for="filter-name">Role</label>
        <input type="text" class="form-control filter-control" name="filter[name]" data-post="name" placeholder="Role">
    </div>
@endsection